keys:
  - &admin_mk age1mrve8n8d5v8ra9alqz83dsghvghs3sa47wu95875gdj7hmd9c4qsj89tjf
  - &admin_mox age13uwx0chvtvafhpxyqld9kwxdeqy8m5gwgraw5wh4kg4qz0l92ynq8rgzfr
  - &admin_kimo age1kh8vpu6jys4w3exl0xyykaztvrmq4p7259falxahnlrqysk4scesfz637q
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_mk
      - *admin_mox
      - *admin_kimo
